---
title: "Kaggle CO2"
output:
  pdf_document: default
  html_document: default
date: "2023-08-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results="hide")
```

```{r}
train <- read.csv("train.csv")
test <- read.csv("test.csv")

library(dplyr)
all <- colnames(train[6:75])
AA <- as.data.frame(train[is.na(train[,6])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_column_number_density)))
BB <- as.data.frame(train[is.na(train[,7])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_column_number_density_amf)))
CC <- as.data.frame(train[is.na(train[,8])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_slant_column_number_density)))
DD <- as.data.frame(train[is.na(train[,9])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_cloud_fraction)))
EE <- as.data.frame(train[is.na(train[,10])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_sensor_azimuth_angle)))
FF <- as.data.frame(train[is.na(train[,11])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_sensor_zenith_angle)))
GG <- as.data.frame(train[is.na(train[,12])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_solar_azimuth_angle)))
HH <- as.data.frame(train[is.na(train[,13])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_solar_zenith_angle)))
II <- as.data.frame(train[is.na(train[,14])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_column_number_density_15km)))
JJ <- as.data.frame(train[is.na(train[,15])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_CO_column_number_density)))
KK <- as.data.frame(train[is.na(train[,16])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_H2O_column_number_density)))
LL <- as.data.frame(train[is.na(train[,17])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_cloud_height)))
MM <- as.data.frame(train[is.na(train[,18])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_sensor_altitude)))
NN <- as.data.frame(train[is.na(train[,19])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_sensor_azimuth_angle)))
OO <- as.data.frame(train[is.na(train[,20])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_sensor_zenith_angle)))
PP <- as.data.frame(train[is.na(train[,21])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_solar_azimuth_angle)))
QQ <- as.data.frame(train[is.na(train[,22])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_solar_zenith_angle)))
RR <- as.data.frame(train[is.na(train[,23])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_NO2_column_number_density)))
SS <- as.data.frame(train[is.na(train[,24])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_tropospheric_NO2_column_number_density)))
TT <- as.data.frame(train[is.na(train[,25])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_stratospheric_NO2_column_number_density)))
UU <- as.data.frame(train[is.na(train[,26])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_NO2_slant_column_number_density)))
VV <- as.data.frame(train[is.na(train[,27])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_tropopause_pressure)))
WW <- as.data.frame(train[is.na(train[,28])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_absorbing_aerosol_index)))
XX <- as.data.frame(train[is.na(train[,29])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_cloud_fraction)))
YY <- as.data.frame(train[is.na(train[,30])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_sensor_altitude)))
ZZ <- as.data.frame(train[is.na(train[,31])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_sensor_azimuth_angle)))
AAA <- as.data.frame(train[is.na(train[,32])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_sensor_zenith_angle)))
BBB <- as.data.frame(train[is.na(train[,33])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_solar_azimuth_angle)))
CCC <- as.data.frame(train[is.na(train[,34])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_solar_zenith_angle)))
DDD <- as.data.frame(train[is.na(train[,35])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_tropospheric_HCHO_column_number_density)))
EEE <- as.data.frame(train[is.na(train[,36])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_tropospheric_HCHO_column_number_density_amf)))
FFF <- as.data.frame(train[is.na(train[,37])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_HCHO_slant_column_number_density)))
GGG <- as.data.frame(train[is.na(train[,38])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_cloud_fraction)))
HHH <- as.data.frame(train[is.na(train[,39])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_solar_zenith_angle)))
III <- as.data.frame(train[is.na(train[,40])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_solar_azimuth_angle)))
JJJ <- as.data.frame(train[is.na(train[,41])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_sensor_zenith_angle)))
KKK <- as.data.frame(train[is.na(train[,42])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_sensor_azimuth_angle)))
LLL <- as.data.frame(train[is.na(train[,43])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_absorbing_aerosol_index)))
MMM <- as.data.frame(train[is.na(train[,44])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_sensor_altitude)))
NNN <- as.data.frame(train[is.na(train[,45])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_sensor_azimuth_angle)))
OOO <- as.data.frame(train[is.na(train[,46])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_sensor_zenith_angle)))
PPP <- as.data.frame(train[is.na(train[,47])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_solar_azimuth_angle)))
QQQ <- as.data.frame(train[is.na(train[,48])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_solar_zenith_angle)))
RRR <- as.data.frame(train[is.na(train[,49])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_column_number_density)))
SSS <- as.data.frame(train[is.na(train[,50])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_column_number_density_amf)))
TTT <- as.data.frame(train[is.na(train[,51])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_slant_column_number_density)))
UUU <- as.data.frame(train[is.na(train[,52])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_effective_temperature)))
VVV <- as.data.frame(train[is.na(train[,53])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_cloud_fraction)))
WWW <- as.data.frame(train[is.na(train[,54])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_sensor_azimuth_angle)))
XXX <- as.data.frame(train[is.na(train[,55])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_sensor_zenith_angle)))
YYY <- as.data.frame(train[is.na(train[,56])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_solar_azimuth_angle)))
ZZZ <- as.data.frame(train[is.na(train[,57])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_solar_zenith_angle)))
AAAA <- as.data.frame(train[is.na(train[,58])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_aerosol_height)))
BBBB <- as.data.frame(train[is.na(train[,59])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_aerosol_pressure)))
CCCC <- as.data.frame(train[is.na(train[,60])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_aerosol_optical_depth)))
DDDD <- as.data.frame(train[is.na(train[,61])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_sensor_zenith_angle)))
EEEE <- as.data.frame(train[is.na(train[,62])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_sensor_azimuth_angle)))
FFFF <- as.data.frame(train[is.na(train[,63])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_solar_azimuth_angle)))
GGGG <- as.data.frame(train[is.na(train[,64])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_solar_zenith_angle)))
HHHH <- as.data.frame(train[is.na(train[,65])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_fraction)))
IIII <- as.data.frame(train[is.na(train[,66])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_top_pressure)))
JJJJ <- as.data.frame(train[is.na(train[,67])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_top_height)))
KKKK <- as.data.frame(train[is.na(train[,68])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_base_pressure)))
LLLL <- as.data.frame(train[is.na(train[,69])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_base_height)))
MMMM <- as.data.frame(train[is.na(train[,70])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_optical_depth)))
NNNN <- as.data.frame(train[is.na(train[,71])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_surface_albedo)))
OOOO <- as.data.frame(train[is.na(train[,72])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_sensor_azimuth_angle)))
PPPP <- as.data.frame(train[is.na(train[,73])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_sensor_zenith_angle)))
QQQQ <- as.data.frame(train[is.na(train[,74])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_solar_azimuth_angle)))
RRRR <- as.data.frame(train[is.na(train[,75])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_solar_zenith_angle)))
AA <- merge(train, AA, all=TRUE)
BB <- merge(train, BB, all=TRUE)
CC <- merge(train, CC, all=TRUE)
DD <- merge(train, DD, all=TRUE)
EE <- merge(train, EE, all=TRUE)
FF <- merge(train, FF, all=TRUE)
GG <- merge(train, GG, all=TRUE)
HH <- merge(train, HH, all=TRUE)
II <- merge(train, II, all=TRUE)
JJ <- merge(train, JJ, all=TRUE)
KK <- merge(train, KK, all=TRUE)
LL <- merge(train, LL, all=TRUE)
MM <- merge(train, MM, all=TRUE)
NN <- merge(train, NN, all=TRUE)
OO <- merge(train, OO, all=TRUE)
PP <- merge(train, PP, all=TRUE)
QQ <- merge(train, QQ, all=TRUE)
RR <- merge(train, RR, all=TRUE)
SS <- merge(train, SS, all=TRUE)
TT <- merge(train, TT, all=TRUE)
UU <- merge(train, UU, all=TRUE)
VV <- merge(train, VV, all=TRUE)
WW <- merge(train, WW, all=TRUE)
XX <- merge(train, XX, all=TRUE)
YY <- merge(train, YY, all=TRUE)
ZZ <- merge(train, ZZ, all=TRUE)
AAA <- merge(train, AAA, all=TRUE)
BBB <- merge(train, BBB, all=TRUE)
CCC <- merge(train, CCC, all=TRUE)
DDD <- merge(train, DDD, all=TRUE)
EEE <- merge(train, EEE, all=TRUE)
FFF <- merge(train, FFF, all=TRUE)
GGG <- merge(train, GGG, all=TRUE)
HHH <- merge(train, HHH, all=TRUE)
III <- merge(train, III, all=TRUE)
JJJ <- merge(train, JJJ, all=TRUE)
KKK <- merge(train, KKK, all=TRUE)
LLL <- merge(train, LLL, all=TRUE)
MMM <- merge(train, MMM, all=TRUE)
NNN <- merge(train, NNN, all=TRUE)
OOO <- merge(train, OOO, all=TRUE)
PPP <- merge(train, PPP, all=TRUE)
QQQ <- merge(train, QQQ, all=TRUE)
RRR <- merge(train, RRR, all=TRUE)
SSS <- merge(train, SSS, all=TRUE)
TTT <- merge(train, TTT, all=TRUE)
UUU <- merge(train, UUU, all=TRUE)
VVV <- merge(train, VVV, all=TRUE)
WWW <- merge(train, WWW, all=TRUE)
XXX <- merge(train, XXX, all=TRUE)
YYY <- merge(train, YYY, all=TRUE)
ZZZ <- merge(train, ZZZ, all=TRUE)
AAAA <- merge(train, AAAA, all=TRUE)
BBBB <- merge(train, BBBB, all=TRUE)
CCCC <- merge(train, CCCC, all=TRUE)
DDDD <- merge(train, DDDD, all=TRUE)
EEEE <- merge(train, EEEE, all=TRUE)
FFFF <- merge(train, FFFF, all=TRUE)
GGGG <- merge(train, GGGG, all=TRUE)
HHHH <- merge(train, HHHH, all=TRUE)
IIII <- merge(train, IIII, all=TRUE)
JJJJ <- merge(train, JJJJ, all=TRUE)
KKKK <- merge(train, KKKK, all=TRUE)
LLLL <- merge(train, LLLL, all=TRUE)
MMMM <- merge(train, MMMM, all=TRUE)
NNNN <- merge(train, NNNN, all=TRUE)
OOOO <- merge(train, OOOO, all=TRUE)
PPPP <- merge(train, PPPP, all=TRUE)
QQQQ <- merge(train, QQQQ, all=TRUE)
RRRR <- merge(train, RRRR, all=TRUE)
train[,6] <- ifelse(is.na(train[,6])==TRUE, AA$a, train[,6])
train[,7] <- ifelse(is.na(train[,7])==TRUE, BB$a, train[,7])
train[,8] <- ifelse(is.na(train[,8])==TRUE, CC$a, train[,8])
train[,9] <- ifelse(is.na(train[,9])==TRUE, DD$a, train[,9])
train[,10] <- ifelse(is.na(train[,10])==TRUE, EE$a, train[,10])
train[,11] <- ifelse(is.na(train[,11])==TRUE, FF$a, train[,11])
train[,12] <- ifelse(is.na(train[,12])==TRUE, GG$a, train[,12])
train[,13] <- ifelse(is.na(train[,13])==TRUE, HH$a, train[,13])
train[,14] <- ifelse(is.na(train[,14])==TRUE, II$a, train[,14])
train[,15] <- ifelse(is.na(train[,15])==TRUE, JJ$a, train[,15])
train[,16] <- ifelse(is.na(train[,16])==TRUE, KK$a, train[,16])
train[,17] <- ifelse(is.na(train[,17])==TRUE, LL$a, train[,17])
train[,18] <- ifelse(is.na(train[,18])==TRUE, MM$a, train[,18])
train[,19] <- ifelse(is.na(train[,19])==TRUE, NN$a, train[,19])
train[,20] <- ifelse(is.na(train[,20])==TRUE, OO$a, train[,20])
train[,21] <- ifelse(is.na(train[,21])==TRUE, PP$a, train[,21])
train[,22] <- ifelse(is.na(train[,22])==TRUE, QQ$a, train[,22])
train[,23] <- ifelse(is.na(train[,23])==TRUE, RR$a, train[,23])
train[,24] <- ifelse(is.na(train[,24])==TRUE, SS$a, train[,24])
train[,25] <- ifelse(is.na(train[,25])==TRUE, TT$a, train[,25])
train[,26] <- ifelse(is.na(train[,26])==TRUE, UU$a, train[,26])
train[,27] <- ifelse(is.na(train[,27])==TRUE, VV$a, train[,27])
train[,28] <- ifelse(is.na(train[,28])==TRUE, WW$a, train[,28])
train[,29] <- ifelse(is.na(train[,29])==TRUE, XX$a, train[,29])
train[,30] <- ifelse(is.na(train[,30])==TRUE, YY$a, train[,30])
train[,31] <- ifelse(is.na(train[,31])==TRUE, ZZ$a, train[,31])
train[,32] <- ifelse(is.na(train[,32])==TRUE, AAA$a, train[,32])
train[,33] <- ifelse(is.na(train[,33])==TRUE, BBB$a, train[,33])
train[,34] <- ifelse(is.na(train[,34])==TRUE, CCC$a, train[,34])
train[,35] <- ifelse(is.na(train[,35])==TRUE, DDD$a, train[,35])
train[,36] <- ifelse(is.na(train[,36])==TRUE, EEE$a, train[,36])
train[,37] <- ifelse(is.na(train[,37])==TRUE, FFF$a, train[,37])
train[,38] <- ifelse(is.na(train[,38])==TRUE, GGG$a, train[,38])
train[,39] <- ifelse(is.na(train[,39])==TRUE, HHH$a, train[,39])
train[,40] <- ifelse(is.na(train[,40])==TRUE, III$a, train[,40])
train[,41] <- ifelse(is.na(train[,41])==TRUE, JJJ$a, train[,41])
train[,42] <- ifelse(is.na(train[,42])==TRUE, KKK$a, train[,42])
train[,43] <- ifelse(is.na(train[,43])==TRUE, LLL$a, train[,43])
train[,44] <- ifelse(is.na(train[,44])==TRUE, MMM$a, train[,44])
train[,45] <- ifelse(is.na(train[,45])==TRUE, NNN$a, train[,45])
train[,46] <- ifelse(is.na(train[,46])==TRUE, OOO$a, train[,46])
train[,47] <- ifelse(is.na(train[,47])==TRUE, PPP$a, train[,47])
train[,48] <- ifelse(is.na(train[,48])==TRUE, QQQ$a, train[,48])
train[,49] <- ifelse(is.na(train[,49])==TRUE, RRR$a, train[,49])
train[,50] <- ifelse(is.na(train[,50])==TRUE, SSS$a, train[,50])
train[,51] <- ifelse(is.na(train[,51])==TRUE, TTT$a, train[,51])
train[,52] <- ifelse(is.na(train[,52])==TRUE, UUU$a, train[,52])
train[,53] <- ifelse(is.na(train[,53])==TRUE, VVV$a, train[,53])
train[,54] <- ifelse(is.na(train[,54])==TRUE, WWW$a, train[,54])
train[,55] <- ifelse(is.na(train[,55])==TRUE, XXX$a, train[,55])
train[,56] <- ifelse(is.na(train[,56])==TRUE, YYY$a, train[,56])
train[,57] <- ifelse(is.na(train[,57])==TRUE, ZZZ$a, train[,57])
train[,58] <- ifelse(is.na(train[,58])==TRUE, AAAA$a, train[,58])
train[,59] <- ifelse(is.na(train[,59])==TRUE, BBBB$a, train[,59])
train[,60] <- ifelse(is.na(train[,60])==TRUE, CCCC$a, train[,60])
train[,61] <- ifelse(is.na(train[,61])==TRUE, DDDD$a, train[,61])
train[,62] <- ifelse(is.na(train[,62])==TRUE, EEEE$a, train[,62])
train[,63] <- ifelse(is.na(train[,63])==TRUE, FFFF$a, train[,63])
train[,64] <- ifelse(is.na(train[,64])==TRUE, GGGG$a, train[,64])
train[,65] <- ifelse(is.na(train[,65])==TRUE, HHHH$a, train[,65])
train[,66] <- ifelse(is.na(train[,66])==TRUE, IIII$a, train[,66])
train[,67] <- ifelse(is.na(train[,67])==TRUE, JJJJ$a, train[,67])
train[,68] <- ifelse(is.na(train[,68])==TRUE, KKKK$a, train[,68])
train[,69] <- ifelse(is.na(train[,69])==TRUE, LLLL$a, train[,69])
train[,70] <- ifelse(is.na(train[,70])==TRUE, MMMM$a, train[,70])
train[,71] <- ifelse(is.na(train[,71])==TRUE, NNNN$a, train[,71])
train[,72] <- ifelse(is.na(train[,72])==TRUE, OOOO$a, train[,72])
train[,73] <- ifelse(is.na(train[,73])==TRUE, PPPP$a, train[,73])
train[,74] <- ifelse(is.na(train[,74])==TRUE, QQQQ$a, train[,74])
train[,75] <- ifelse(is.na(train[,75])==TRUE, RRRR$a, train[,75])
#create new colnames col1


AA <- as.data.frame(test[is.na(test[,6])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_column_number_density)))
BB <- as.data.frame(test[is.na(test[,7])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_column_number_density_amf)))
CC <- as.data.frame(test[is.na(test[,8])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_slant_column_number_density)))
DD <- as.data.frame(test[is.na(test[,9])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_cloud_fraction)))
EE <- as.data.frame(test[is.na(test[,10])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_sensor_azimuth_angle)))
FF <- as.data.frame(test[is.na(test[,11])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_sensor_zenith_angle)))
GG <- as.data.frame(test[is.na(test[,12])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_solar_azimuth_angle)))
HH <- as.data.frame(test[is.na(test[,13])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_solar_zenith_angle)))
II <- as.data.frame(test[is.na(test[,14])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(SulphurDioxide_SO2_column_number_density_15km)))
JJ <- as.data.frame(test[is.na(test[,15])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_CO_column_number_density)))
KK <- as.data.frame(test[is.na(test[,16])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_H2O_column_number_density)))
LL <- as.data.frame(test[is.na(test[,17])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_cloud_height)))
MM <- as.data.frame(test[is.na(test[,18])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_sensor_altitude)))
NN <- as.data.frame(test[is.na(test[,19])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_sensor_azimuth_angle)))
OO <- as.data.frame(test[is.na(test[,20])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_sensor_zenith_angle)))
PP <- as.data.frame(test[is.na(test[,21])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_solar_azimuth_angle)))
QQ <- as.data.frame(test[is.na(test[,22])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(CarbonMonoxide_solar_zenith_angle)))
RR <- as.data.frame(test[is.na(test[,23])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_NO2_column_number_density)))
SS <- as.data.frame(test[is.na(test[,24])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_tropospheric_NO2_column_number_density)))
TT <- as.data.frame(test[is.na(test[,25])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_stratospheric_NO2_column_number_density)))
UU <- as.data.frame(test[is.na(test[,26])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_NO2_slant_column_number_density)))
VV <- as.data.frame(test[is.na(test[,27])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_tropopause_pressure)))
WW <- as.data.frame(test[is.na(test[,28])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_absorbing_aerosol_index)))
XX <- as.data.frame(test[is.na(test[,29])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_cloud_fraction)))
YY <- as.data.frame(test[is.na(test[,30])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_sensor_altitude)))
ZZ <- as.data.frame(test[is.na(test[,31])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_sensor_azimuth_angle)))
AAA <- as.data.frame(test[is.na(test[,32])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_sensor_zenith_angle)))
BBB <- as.data.frame(test[is.na(test[,33])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_solar_azimuth_angle)))
CCC <- as.data.frame(test[is.na(test[,34])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(NitrogenDioxide_solar_zenith_angle)))
DDD <- as.data.frame(test[is.na(test[,35])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_tropospheric_HCHO_column_number_density)))
EEE <- as.data.frame(test[is.na(test[,36])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_tropospheric_HCHO_column_number_density_amf)))
FFF <- as.data.frame(test[is.na(test[,37])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_HCHO_slant_column_number_density)))
GGG <- as.data.frame(test[is.na(test[,38])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_cloud_fraction)))
HHH <- as.data.frame(test[is.na(test[,39])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_solar_zenith_angle)))
III <- as.data.frame(test[is.na(test[,40])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_solar_azimuth_angle)))
JJJ <- as.data.frame(test[is.na(test[,41])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_sensor_zenith_angle)))
KKK <- as.data.frame(test[is.na(test[,42])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Formaldehyde_sensor_azimuth_angle)))
LLL <- as.data.frame(test[is.na(test[,43])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_absorbing_aerosol_index)))
MMM <- as.data.frame(test[is.na(test[,44])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_sensor_altitude)))
NNN <- as.data.frame(test[is.na(test[,45])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_sensor_azimuth_angle)))
OOO <- as.data.frame(test[is.na(test[,46])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_sensor_zenith_angle)))
PPP <- as.data.frame(test[is.na(test[,47])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_solar_azimuth_angle)))
QQQ <- as.data.frame(test[is.na(test[,48])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolIndex_solar_zenith_angle)))
RRR <- as.data.frame(test[is.na(test[,49])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_column_number_density)))
SSS <- as.data.frame(test[is.na(test[,50])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_column_number_density_amf)))
TTT <- as.data.frame(test[is.na(test[,51])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_slant_column_number_density)))
UUU <- as.data.frame(test[is.na(test[,52])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_O3_effective_temperature)))
VVV <- as.data.frame(test[is.na(test[,53])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_cloud_fraction)))
WWW <- as.data.frame(test[is.na(test[,54])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_sensor_azimuth_angle)))
XXX <- as.data.frame(test[is.na(test[,55])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_sensor_zenith_angle)))
YYY <- as.data.frame(test[is.na(test[,56])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_solar_azimuth_angle)))
ZZZ <- as.data.frame(test[is.na(test[,57])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Ozone_solar_zenith_angle)))
AAAA <- as.data.frame(test[is.na(test[,58])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_aerosol_height)))
BBBB <- as.data.frame(test[is.na(test[,59])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_aerosol_pressure)))
CCCC <- as.data.frame(test[is.na(test[,60])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_aerosol_optical_depth)))
DDDD <- as.data.frame(test[is.na(test[,61])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_sensor_zenith_angle)))
EEEE <- as.data.frame(test[is.na(test[,62])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_sensor_azimuth_angle)))
FFFF <- as.data.frame(test[is.na(test[,63])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_solar_azimuth_angle)))
GGGG <- as.data.frame(test[is.na(test[,64])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(UvAerosolLayerHeight_solar_zenith_angle)))
HHHH <- as.data.frame(test[is.na(test[,65])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_fraction)))
IIII <- as.data.frame(test[is.na(test[,66])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_top_pressure)))
JJJJ <- as.data.frame(test[is.na(test[,67])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_top_height)))
KKKK <- as.data.frame(test[is.na(test[,68])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_base_pressure)))
LLLL <- as.data.frame(test[is.na(test[,69])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_base_height)))
MMMM <- as.data.frame(test[is.na(test[,70])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_cloud_optical_depth)))
NNNN <- as.data.frame(test[is.na(test[,71])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_surface_albedo)))
OOOO <- as.data.frame(test[is.na(test[,72])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_sensor_azimuth_angle)))
PPPP <- as.data.frame(test[is.na(test[,73])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_sensor_zenith_angle)))
QQQQ <- as.data.frame(test[is.na(test[,74])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_solar_azimuth_angle)))
RRRR <- as.data.frame(test[is.na(test[,75])==FALSE,] %>% group_by(year, week_no) %>% summarise(a=mean(Cloud_solar_zenith_angle)))
AA <- merge(test, AA, all=TRUE)
BB <- merge(test, BB, all=TRUE)
CC <- merge(test, CC, all=TRUE)
DD <- merge(test, DD, all=TRUE)
EE <- merge(test, EE, all=TRUE)
FF <- merge(test, FF, all=TRUE)
GG <- merge(test, GG, all=TRUE)
HH <- merge(test, HH, all=TRUE)
II <- merge(test, II, all=TRUE)
JJ <- merge(test, JJ, all=TRUE)
KK <- merge(test, KK, all=TRUE)
LL <- merge(test, LL, all=TRUE)
MM <- merge(test, MM, all=TRUE)
NN <- merge(test, NN, all=TRUE)
OO <- merge(test, OO, all=TRUE)
PP <- merge(test, PP, all=TRUE)
QQ <- merge(test, QQ, all=TRUE)
RR <- merge(test, RR, all=TRUE)
SS <- merge(test, SS, all=TRUE)
TT <- merge(test, TT, all=TRUE)
UU <- merge(test, UU, all=TRUE)
VV <- merge(test, VV, all=TRUE)
WW <- merge(test, WW, all=TRUE)
XX <- merge(test, XX, all=TRUE)
YY <- merge(test, YY, all=TRUE)
ZZ <- merge(test, ZZ, all=TRUE)
AAA <- merge(test, AAA, all=TRUE)
BBB <- merge(test, BBB, all=TRUE)
CCC <- merge(test, CCC, all=TRUE)
DDD <- merge(test, DDD, all=TRUE)
EEE <- merge(test, EEE, all=TRUE)
FFF <- merge(test, FFF, all=TRUE)
GGG <- merge(test, GGG, all=TRUE)
HHH <- merge(test, HHH, all=TRUE)
III <- merge(test, III, all=TRUE)
JJJ <- merge(test, JJJ, all=TRUE)
KKK <- merge(test, KKK, all=TRUE)
LLL <- merge(test, LLL, all=TRUE)
MMM <- merge(test, MMM, all=TRUE)
NNN <- merge(test, NNN, all=TRUE)
OOO <- merge(test, OOO, all=TRUE)
PPP <- merge(test, PPP, all=TRUE)
QQQ <- merge(test, QQQ, all=TRUE)
RRR <- merge(test, RRR, all=TRUE)
SSS <- merge(test, SSS, all=TRUE)
TTT <- merge(test, TTT, all=TRUE)
UUU <- merge(test, UUU, all=TRUE)
VVV <- merge(test, VVV, all=TRUE)
WWW <- merge(test, WWW, all=TRUE)
XXX <- merge(test, XXX, all=TRUE)
YYY <- merge(test, YYY, all=TRUE)
ZZZ <- merge(test, ZZZ, all=TRUE)
AAAA <- merge(test, AAAA, all=TRUE)
BBBB <- merge(test, BBBB, all=TRUE)
CCCC <- merge(test, CCCC, all=TRUE)
DDDD <- merge(test, DDDD, all=TRUE)
EEEE <- merge(test, EEEE, all=TRUE)
FFFF <- merge(test, FFFF, all=TRUE)
GGGG <- merge(test, GGGG, all=TRUE)
HHHH <- merge(test, HHHH, all=TRUE)
IIII <- merge(test, IIII, all=TRUE)
JJJJ <- merge(test, JJJJ, all=TRUE)
KKKK <- merge(test, KKKK, all=TRUE)
LLLL <- merge(test, LLLL, all=TRUE)
MMMM <- merge(test, MMMM, all=TRUE)
NNNN <- merge(test, NNNN, all=TRUE)
OOOO <- merge(test, OOOO, all=TRUE)
PPPP <- merge(test, PPPP, all=TRUE)
QQQQ <- merge(test, QQQQ, all=TRUE)
RRRR <- merge(test, RRRR, all=TRUE)
test[,6] <- ifelse(is.na(test[,6])==TRUE, AA$a, test[,6])
test[,7] <- ifelse(is.na(test[,7])==TRUE, BB$a, test[,7])
test[,8] <- ifelse(is.na(test[,8])==TRUE, CC$a, test[,8])
test[,9] <- ifelse(is.na(test[,9])==TRUE, DD$a, test[,9])
test[,10] <- ifelse(is.na(test[,10])==TRUE, EE$a, test[,10])
test[,11] <- ifelse(is.na(test[,11])==TRUE, FF$a, test[,11])
test[,12] <- ifelse(is.na(test[,12])==TRUE, GG$a, test[,12])
test[,13] <- ifelse(is.na(test[,13])==TRUE, HH$a, test[,13])
test[,14] <- ifelse(is.na(test[,14])==TRUE, II$a, test[,14])
test[,15] <- ifelse(is.na(test[,15])==TRUE, JJ$a, test[,15])
test[,16] <- ifelse(is.na(test[,16])==TRUE, KK$a, test[,16])
test[,17] <- ifelse(is.na(test[,17])==TRUE, LL$a, test[,17])
test[,18] <- ifelse(is.na(test[,18])==TRUE, MM$a, test[,18])
test[,19] <- ifelse(is.na(test[,19])==TRUE, NN$a, test[,19])
test[,20] <- ifelse(is.na(test[,20])==TRUE, OO$a, test[,20])
test[,21] <- ifelse(is.na(test[,21])==TRUE, PP$a, test[,21])
test[,22] <- ifelse(is.na(test[,22])==TRUE, QQ$a, test[,22])
test[,23] <- ifelse(is.na(test[,23])==TRUE, RR$a, test[,23])
test[,24] <- ifelse(is.na(test[,24])==TRUE, SS$a, test[,24])
test[,25] <- ifelse(is.na(test[,25])==TRUE, TT$a, test[,25])
test[,26] <- ifelse(is.na(test[,26])==TRUE, UU$a, test[,26])
test[,27] <- ifelse(is.na(test[,27])==TRUE, VV$a, test[,27])
test[,28] <- ifelse(is.na(test[,28])==TRUE, WW$a, test[,28])
test[,29] <- ifelse(is.na(test[,29])==TRUE, XX$a, test[,29])
test[,30] <- ifelse(is.na(test[,30])==TRUE, YY$a, test[,30])
test[,31] <- ifelse(is.na(test[,31])==TRUE, ZZ$a, test[,31])
test[,32] <- ifelse(is.na(test[,32])==TRUE, AAA$a, test[,32])
test[,33] <- ifelse(is.na(test[,33])==TRUE, BBB$a, test[,33])
test[,34] <- ifelse(is.na(test[,34])==TRUE, CCC$a, test[,34])
test[,35] <- ifelse(is.na(test[,35])==TRUE, DDD$a, test[,35])
test[,36] <- ifelse(is.na(test[,36])==TRUE, EEE$a, test[,36])
test[,37] <- ifelse(is.na(test[,37])==TRUE, FFF$a, test[,37])
test[,38] <- ifelse(is.na(test[,38])==TRUE, GGG$a, test[,38])
test[,39] <- ifelse(is.na(test[,39])==TRUE, HHH$a, test[,39])
test[,40] <- ifelse(is.na(test[,40])==TRUE, III$a, test[,40])
test[,41] <- ifelse(is.na(test[,41])==TRUE, JJJ$a, test[,41])
test[,42] <- ifelse(is.na(test[,42])==TRUE, KKK$a, test[,42])
test[,43] <- ifelse(is.na(test[,43])==TRUE, LLL$a, test[,43])
test[,44] <- ifelse(is.na(test[,44])==TRUE, MMM$a, test[,44])
test[,45] <- ifelse(is.na(test[,45])==TRUE, NNN$a, test[,45])
test[,46] <- ifelse(is.na(test[,46])==TRUE, OOO$a, test[,46])
test[,47] <- ifelse(is.na(test[,47])==TRUE, PPP$a, test[,47])
test[,48] <- ifelse(is.na(test[,48])==TRUE, QQQ$a, test[,48])
test[,49] <- ifelse(is.na(test[,49])==TRUE, RRR$a, test[,49])
test[,50] <- ifelse(is.na(test[,50])==TRUE, SSS$a, test[,50])
test[,51] <- ifelse(is.na(test[,51])==TRUE, TTT$a, test[,51])
test[,52] <- ifelse(is.na(test[,52])==TRUE, UUU$a, test[,52])
test[,53] <- ifelse(is.na(test[,53])==TRUE, VVV$a, test[,53])
test[,54] <- ifelse(is.na(test[,54])==TRUE, WWW$a, test[,54])
test[,55] <- ifelse(is.na(test[,55])==TRUE, XXX$a, test[,55])
test[,56] <- ifelse(is.na(test[,56])==TRUE, YYY$a, test[,56])
test[,57] <- ifelse(is.na(test[,57])==TRUE, ZZZ$a, test[,57])
test[,58] <- ifelse(is.na(test[,58])==TRUE, AAAA$a, test[,58])
test[,59] <- ifelse(is.na(test[,59])==TRUE, BBBB$a, test[,59])
test[,60] <- ifelse(is.na(test[,60])==TRUE, CCCC$a, test[,60])
test[,61] <- ifelse(is.na(test[,61])==TRUE, DDDD$a, test[,61])
test[,62] <- ifelse(is.na(test[,62])==TRUE, EEEE$a, test[,62])
test[,63] <- ifelse(is.na(test[,63])==TRUE, FFFF$a, test[,63])
test[,64] <- ifelse(is.na(test[,64])==TRUE, GGGG$a, test[,64])
test[,65] <- ifelse(is.na(test[,65])==TRUE, HHHH$a, test[,65])
test[,66] <- ifelse(is.na(test[,66])==TRUE, IIII$a, test[,66])
test[,67] <- ifelse(is.na(test[,67])==TRUE, JJJJ$a, test[,67])
test[,68] <- ifelse(is.na(test[,68])==TRUE, KKKK$a, test[,68])
test[,69] <- ifelse(is.na(test[,69])==TRUE, LLLL$a, test[,69])
test[,70] <- ifelse(is.na(test[,70])==TRUE, MMMM$a, test[,70])
test[,71] <- ifelse(is.na(test[,71])==TRUE, NNNN$a, test[,71])
test[,72] <- ifelse(is.na(test[,72])==TRUE, OOOO$a, test[,72])
test[,73] <- ifelse(is.na(test[,73])==TRUE, PPPP$a, test[,73])
test[,74] <- ifelse(is.na(test[,74])==TRUE, QQQQ$a, test[,74])
test[,75] <- ifelse(is.na(test[,75])==TRUE, RRRR$a, test[,75])
```


```{r}
#feature engineering
# AA <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_column_number_density)))
# BB <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_column_number_density_amf)))
# CC <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_slant_column_number_density)))
# DD <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_cloud_fraction)))
# EE <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_sensor_azimuth_angle)))
# FF <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_sensor_zenith_angle)))
# GG <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_solar_azimuth_angle)))
# HH <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_solar_zenith_angle)))
# II <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_column_number_density_15km)))
JJ <- as.data.frame(train %>% group_by(latitude, longitude, year) %>% summarise(sum(CarbonMonoxide_CO_column_number_density)))
# KK <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_H2O_column_number_density)))
# LL <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_cloud_height)))
# MM <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_sensor_altitude)))
# NN <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_sensor_azimuth_angle)))
# OO <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_sensor_zenith_angle)))
# PP <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_solar_azimuth_angle)))
# QQ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_solar_zenith_angle)))
RR <- as.data.frame(train %>% group_by(latitude, longitude, year) %>% summarise(sum(NitrogenDioxide_NO2_column_number_density)))
# SS <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_tropospheric_NO2_column_number_density)))
# TT <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_stratospheric_NO2_column_number_density)))
# UU <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_NO2_slant_column_number_density)))
# VV <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_tropopause_pressure)))
# WW <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_absorbing_aerosol_index)))
# XX <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_cloud_fraction)))
# YY <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_sensor_altitude)))
# ZZ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_sensor_azimuth_angle)))
# AAA <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_sensor_zenith_angle)))
# BBB <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_solar_azimuth_angle)))
# CCC <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_solar_zenith_angle)))
DDD <- as.data.frame(train %>% group_by(latitude, longitude, year) %>% summarise(sum(Formaldehyde_tropospheric_HCHO_column_number_density)))
# EEE <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_tropospheric_HCHO_column_number_density_amf)))
# FFF <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_HCHO_slant_column_number_density)))
# GGG <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_cloud_fraction)))
# HHH <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_solar_zenith_angle)))
# III <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_solar_azimuth_angle)))
# JJJ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_sensor_zenith_angle)))
# KKK <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_sensor_azimuth_angle)))
# LLL <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_absorbing_aerosol_index)))
# MMM <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_sensor_altitude)))
# NNN <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_sensor_azimuth_angle)))
# OOO <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_sensor_zenith_angle)))
# PPP <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_solar_azimuth_angle)))
# QQQ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_solar_zenith_angle)))
RRR <- as.data.frame(train %>% group_by(latitude, longitude, year) %>% summarise(sum(Ozone_O3_column_number_density)))
# SSS <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_O3_column_number_density_amf)))
# TTT <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_O3_slant_column_number_density)))
# UUU <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_O3_effective_temperature)))
# VVV <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_cloud_fraction)))
# WWW <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_sensor_azimuth_angle)))
# XXX <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_sensor_zenith_angle)))
# YYY <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_solar_azimuth_angle)))
# ZZZ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_solar_zenith_angle)))
# AAAA <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_aerosol_height)))
# BBBB <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_aerosol_pressure)))
# CCCC <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_aerosol_optical_depth)))
# DDDD <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_sensor_zenith_angle)))
# EEEE <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_sensor_azimuth_angle)))
# FFFF <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_solar_azimuth_angle)))
# GGGG <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_solar_zenith_angle)))
# HHHH <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_fraction)))
# IIII <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_top_pressure)))
# JJJJ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_top_height)))
# KKKK <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_base_pressure)))
# LLLL <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_base_height)))
# MMMM <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_optical_depth)))
# NNNN <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_surface_albedo)))
# OOOO <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_sensor_azimuth_angle)))
# PPPP <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_sensor_zenith_angle)))
# QQQQ <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_solar_azimuth_angle)))
# RRRR <- as.data.frame(train %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_solar_zenith_angle)))
# train <- merge(train, AA, all=TRUE)
# train <- merge(train, BB, all=TRUE)
# train <- merge(train, CC, all=TRUE)
# train <- merge(train, DD, all=TRUE)
# train <- merge(train, EE, all=TRUE)
# train <- merge(train, FF, all=TRUE)
# train <- merge(train, GG, all=TRUE)
# train <- merge(train, HH, all=TRUE)
# train <- merge(train, II, all=TRUE)
train <- merge(train, JJ, all=TRUE)
# train <- merge(train, KK, all=TRUE)
# train <- merge(train, LL, all=TRUE)
# train <- merge(train, MM, all=TRUE)
# train <- merge(train, NN, all=TRUE)
# train <- merge(train, OO, all=TRUE)
# train <- merge(train, PP, all=TRUE)
# train <- merge(train, QQ, all=TRUE)
train <- merge(train, RR, all=TRUE)
# train <- merge(train, SS, all=TRUE)
# train <- merge(train, TT, all=TRUE)
# train <- merge(train, UU, all=TRUE)
# train <- merge(train, VV, all=TRUE)
# train <- merge(train, WW, all=TRUE)
# train <- merge(train, XX, all=TRUE)
# train <- merge(train, YY, all=TRUE)
# train <- merge(train, ZZ, all=TRUE)
# train <- merge(train, AAA, all=TRUE)
# train <- merge(train, BBB, all=TRUE)
# train <- merge(train, CCC, all=TRUE)
train <- merge(train, DDD, all=TRUE)
# train <- merge(train, EEE, all=TRUE)
# train <- merge(train, FFF, all=TRUE)
# train <- merge(train, GGG, all=TRUE)
# train <- merge(train, HHH, all=TRUE)
# train <- merge(train, III, all=TRUE)
# train <- merge(train, JJJ, all=TRUE)
# train <- merge(train, KKK, all=TRUE)
# train <- merge(train, LLL, all=TRUE)
# train <- merge(train, MMM, all=TRUE)
# train <- merge(train, NNN, all=TRUE)
# train <- merge(train, OOO, all=TRUE)
# train <- merge(train, PPP, all=TRUE)
# train <- merge(train, QQQ, all=TRUE)
train <- merge(train, RRR, all=TRUE)
# train <- merge(train, SSS, all=TRUE)
# train <- merge(train, TTT, all=TRUE)
# train <- merge(train, UUU, all=TRUE)
# train <- merge(train, VVV, all=TRUE)
# train <- merge(train, WWW, all=TRUE)
# train <- merge(train, XXX, all=TRUE)
# train <- merge(train, YYY, all=TRUE)
# train <- merge(train, ZZZ, all=TRUE)
# train <- merge(train, AAAA, all=TRUE)
# train <- merge(train, BBBB, all=TRUE)
# train <- merge(train, CCCC, all=TRUE)
# train <- merge(train, DDDD, all=TRUE)
# train <- merge(train, EEEE, all=TRUE)
# train <- merge(train, FFFF, all=TRUE)
# train <- merge(train, GGGG, all=TRUE)
# train <- merge(train, HHHH, all=TRUE)
# train <- merge(train, IIII, all=TRUE)
# train <- merge(train, JJJJ, all=TRUE)
# train <- merge(train, KKKK, all=TRUE)
# train <- merge(train, LLLL, all=TRUE)
# train <- merge(train, MMMM, all=TRUE)
# train <- merge(train, NNNN, all=TRUE)
# train <- merge(train, OOOO, all=TRUE)
# train <- merge(train, PPPP, all=TRUE)
# train <- merge(train, QQQQ, all=TRUE)
# train <- merge(train, RRRR, all=TRUE)


# AA <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_column_number_density)))
# BB <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_column_number_density_amf)))
# CC <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_slant_column_number_density)))
# DD <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_cloud_fraction)))
# EE <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_sensor_azimuth_angle)))
# FF <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_sensor_zenith_angle)))
# GG <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_solar_azimuth_angle)))
# HH <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_solar_zenith_angle)))
# II <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(SulphurDioxide_SO2_column_number_density_15km)))
JJ <- as.data.frame(test %>% group_by(latitude, longitude, year) %>% summarise(sum(CarbonMonoxide_CO_column_number_density)))
# KK <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_H2O_column_number_density)))
# LL <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_cloud_height)))
# MM <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_sensor_altitude)))
# NN <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_sensor_azimuth_angle)))
# OO <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_sensor_zenith_angle)))
# PP <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_solar_azimuth_angle)))
# QQ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(CarbonMonoxide_solar_zenith_angle)))
RR <- as.data.frame(test %>% group_by(latitude, longitude, year) %>% summarise(sum(NitrogenDioxide_NO2_column_number_density)))
# SS <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_tropospheric_NO2_column_number_density)))
# TT <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_stratospheric_NO2_column_number_density)))
# UU <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_NO2_slant_column_number_density)))
# VV <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_tropopause_pressure)))
# WW <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_absorbing_aerosol_index)))
# XX <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_cloud_fraction)))
# YY <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_sensor_altitude)))
# ZZ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_sensor_azimuth_angle)))
# AAA <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_sensor_zenith_angle)))
# BBB <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_solar_azimuth_angle)))
# CCC <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(NitrogenDioxide_solar_zenith_angle)))
DDD <- as.data.frame(test %>% group_by(latitude, longitude, year) %>% summarise(sum(Formaldehyde_tropospheric_HCHO_column_number_density)))
# EEE <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_tropospheric_HCHO_column_number_density_amf)))
# FFF <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_HCHO_slant_column_number_density)))
# GGG <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_cloud_fraction)))
# HHH <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_solar_zenith_angle)))
# III <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_solar_azimuth_angle)))
# JJJ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_sensor_zenith_angle)))
# KKK <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Formaldehyde_sensor_azimuth_angle)))
# LLL <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_absorbing_aerosol_index)))
# MMM <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_sensor_altitude)))
# NNN <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_sensor_azimuth_angle)))
# OOO <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_sensor_zenith_angle)))
# PPP <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_solar_azimuth_angle)))
# QQQ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolIndex_solar_zenith_angle)))
RRR <- as.data.frame(test %>% group_by(latitude, longitude, year) %>% summarise(sum(Ozone_O3_column_number_density)))
# SSS <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_O3_column_number_density_amf)))
# TTT <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_O3_slant_column_number_density)))
# UUU <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_O3_effective_temperature)))
# VVV <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_cloud_fraction)))
# WWW <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_sensor_azimuth_angle)))
# XXX <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_sensor_zenith_angle)))
# YYY <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_solar_azimuth_angle)))
# ZZZ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Ozone_solar_zenith_angle)))
# AAAA <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_aerosol_height)))
# BBBB <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_aerosol_pressure)))
# CCCC <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_aerosol_optical_depth)))
# DDDD <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_sensor_zenith_angle)))
# EEEE <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_sensor_azimuth_angle)))
# FFFF <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_solar_azimuth_angle)))
# GGGG <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(UvAerosolLayerHeight_solar_zenith_angle)))
# HHHH <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_fraction)))
# IIII <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_top_pressure)))
# JJJJ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_top_height)))
# KKKK <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_base_pressure)))
# LLLL <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_base_height)))
# MMMM <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_cloud_optical_depth)))
# NNNN <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_surface_albedo)))
# OOOO <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_sensor_azimuth_angle)))
# PPPP <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_sensor_zenith_angle)))
# QQQQ <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_solar_azimuth_angle)))
# RRRR <- as.data.frame(test %>% group_by(latitude, longitude) %>% summarise(sum(Cloud_solar_zenith_angle)))
# test <- merge(test, AA, all=TRUE)
# test <- merge(test, BB, all=TRUE)
# test <- merge(test, CC, all=TRUE)
# test <- merge(test, DD, all=TRUE)
# test <- merge(test, EE, all=TRUE)
# test <- merge(test, FF, all=TRUE)
# test <- merge(test, GG, all=TRUE)
# test <- merge(test, HH, all=TRUE)
# test <- merge(test, II, all=TRUE)
test <- merge(test, JJ, all=TRUE)
# test <- merge(test, KK, all=TRUE)
# test <- merge(test, LL, all=TRUE)
# test <- merge(test, MM, all=TRUE)
# test <- merge(test, NN, all=TRUE)
# test <- merge(test, OO, all=TRUE)
# test <- merge(test, PP, all=TRUE)
# test <- merge(test, QQ, all=TRUE)
test <- merge(test, RR, all=TRUE)
# test <- merge(test, SS, all=TRUE)
# test <- merge(test, TT, all=TRUE)
# test <- merge(test, UU, all=TRUE)
# test <- merge(test, VV, all=TRUE)
# test <- merge(test, WW, all=TRUE)
# test <- merge(test, XX, all=TRUE)
# test <- merge(test, YY, all=TRUE)
# test <- merge(test, ZZ, all=TRUE)
# test <- merge(test, AAA, all=TRUE)
# test <- merge(test, BBB, all=TRUE)
# test <- merge(test, CCC, all=TRUE)
test <- merge(test, DDD, all=TRUE)
# test <- merge(test, EEE, all=TRUE)
# test <- merge(test, FFF, all=TRUE)
# test <- merge(test, GGG, all=TRUE)
# test <- merge(test, HHH, all=TRUE)
# test <- merge(test, III, all=TRUE)
# test <- merge(test, JJJ, all=TRUE)
# test <- merge(test, KKK, all=TRUE)
# test <- merge(test, LLL, all=TRUE)
# test <- merge(test, MMM, all=TRUE)
# test <- merge(test, NNN, all=TRUE)
# test <- merge(test, OOO, all=TRUE)
# test <- merge(test, PPP, all=TRUE)
# test <- merge(test, QQQ, all=TRUE)
test <- merge(test, RRR, all=TRUE)
# test <- merge(test, SSS, all=TRUE)
# test <- merge(test, TTT, all=TRUE)
# test <- merge(test, UUU, all=TRUE)
# test <- merge(test, VVV, all=TRUE)
# test <- merge(test, WWW, all=TRUE)
# test <- merge(test, XXX, all=TRUE)
# test <- merge(test, YYY, all=TRUE)
# test <- merge(test, ZZZ, all=TRUE)
# test <- merge(test, AAAA, all=TRUE)
# test <- merge(test, BBBB, all=TRUE)
# test <- merge(test, CCCC, all=TRUE)
# test <- merge(test, DDDD, all=TRUE)
# test <- merge(test, EEEE, all=TRUE)
# test <- merge(test, FFFF, all=TRUE)
# test <- merge(test, GGGG, all=TRUE)
# test <- merge(test, HHHH, all=TRUE)
# test <- merge(test, IIII, all=TRUE)
# test <- merge(test, JJJJ, all=TRUE)
# test <- merge(test, KKKK, all=TRUE)
# test <- merge(test, LLLL, all=TRUE)
# test <- merge(test, MMMM, all=TRUE)
# test <- merge(test, NNNN, all=TRUE)
# test <- merge(test, OOOO, all=TRUE)
# test <- merge(test, PPPP, all=TRUE)
# test <- merge(test, QQQQ, all=TRUE)
# test <- merge(test, RRRR, all=TRUE)
train
```

```{r}
library(xgboost)
model <- xgboost(data=as.matrix(train[,-c(4,76)]), label=as.matrix(train[,76]), nrounds=300)
prediction <- predict(model, as.matrix(test[,-4]), type="response")
write.csv(data.frame(ID_LAT_LON_YEAR_WEEK=test$ID_LAT_LON_YEAR_WEEK, emission=ifelse(prediction<0, 0, prediction)), "xgboost3.csv", row.names=FALSE)
x <- read.csv("xgboost3.csv")
library(ggplot2)
library(dplyr)
xx <- train %>% group_by(year) %>% summarise(emission=sum(emission))
ggplot(xx, aes(x=year, y=emission)) + geom_line() + geom_point()
summary(x)
train
```